import './login.js';                        console.log("Logando na     Twitch...");
import './comandos.js';                     console.log("Inicializando  Comandos...");
import "./audios.js";                       console.log("Carregando     Audios...");
import './calculadora.js';                  console.log("Abrindo        Calculadora...");
import './primeiraMensagem.js';             console.log("Carregando     Primeiras Mensagens...");
import './palavroes.js';                    console.log("Filtrando      Palavrões...");
import './discord.js';                      console.log("Entrando no    Discord...");
import './dj.js';                           console.log("Caregando      Dj...");
import './mortes.js';                       console.log("Contabilizando Mortes...");
import './subResub.js';                     console.log("Lendo          Resubs...");
import './rewards.js';                      console.log("Aguardando     Rewards...");
import './bits.js';                         console.log("Computando     Bits...");
import './ad.js';                           console.log("Contando       Ads...");
import './cargos.js';                       console.log("Selecionando   Cargos...");
import './contadorDeMensagens.js';          console.log("Contando       Mensagens...");
import './respostasAlternativas.js';        console.log("Alternando     Respostas...");
//import './Voz/comandos.js';                 console.log("Ouvindo        Voz...");